# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\VCS\Model\Commit:
    type: entity
    repositoryClass: Kreta\Component\VCS\Repository\CommitRepository
    table: commit
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        author:
            type: string
            length: 50
        message:
            type: text
        sha:
            type: string
            length: 50
        url:
            type: string
    manyToOne:
        branch:
            targetEntity: Kreta\Component\VCS\Model\Interfaces\BranchInterface
            joinColumn:
                name: branch_id
                referencedColumnName: id
    manyToMany:
        issuesRelated:
            targetEntity: Kreta\Component\Issue\Model\Interfaces\IssueInterface
            joinTable:
                name: commit_issues
                joinColumns:
                  commit_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  issue_id:
                    referencedColumnName: id
