# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_vcs.repository.issue:
        class: %kreta_vcs.repository_issue.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %kreta_issue.issue.class%

    kreta_vcs.repository.commit:
        class: %kreta_vcs.repository_commit.class%
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - %kreta_vcs.commit.class%
    kreta_vcs.repository.branch:
        class: %kreta_vcs.repository_branch.class%
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - %kreta_vcs.branch.class%
    kreta_vcs.repository.repository:
        class: %kreta_vcs.repository_repository.class%
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - %kreta_vcs.repository.class%
