# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\VCS\Model\Branch:
    exclusion_policy: ALL
    relations:
        -
            rel: branches
            href:
                route: get_issues_branches
                parameters:
                    issueId: expr(object.getIssuesRelated()[0].getId())
                absolute: true
            exclusion:
                groups: [branchList]
        -
            rel: issue
            href:
                route: get_issue
                parameters:
                    issueId: expr(object.getIssuesRelated()[0].getId())
                absolute: true
            exclusion:
                groups: [branchList]
    properties:
        id:
            expose: true
            groups: [branchList, commitList]
        name:
            expose: true
            groups: [branchList, commitList]
        repository:
            expose: true
            groups: [branchList, commitList]
        issuesRelated:
            expose: true
            groups: []
